apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - client.yaml
  - posts.yaml
  - comments.yaml
  - query.yaml
  - moderation.yaml
  - event-bus.yaml
  - ingress.yaml

images:
  - name: client
    newName: client
    newTag: latest
  - name: posts
    newName: posts
    newTag: latest
  - name: comments
    newName: comments
    newTag: latest
  - name: query
    newName: query
    newTag: latest
  - name: moderation
    newName: moderation
    newTag: latest
  - name: event-bus
    newName: event-bus
    newTag: latest
